@echo off
setlocal EnableExtensions EnableDelayedExpansion

REM Usage:
REM   packaging\scripts\make_installer_win.bat "<build_dir>" "<source_dir>"

set "BUILD_DIR=%~1"
set "SRC_DIR=%~2"

if "%BUILD_DIR%"=="" (
  echo [ERROR] BUILD_DIR missing
  exit /b 1
)
if "%SRC_DIR%"=="" (
  echo [ERROR] SRC_DIR missing
  exit /b 1
)

REM Load env generated by CMake
set "ENV_FILE=%BUILD_DIR%\packaging\packaging.env.bat"
if not exist "%ENV_FILE%" (
  echo [ERROR] Missing %ENV_FILE%
  echo [HINT] Re-run CMake configure to generate build\packaging\packaging.env.bat
  exit /b 1
)
call "%ENV_FILE%"

REM Normalize Qt path separators (CMake may emit /)
set "QT_ROOT=%QT_ROOT:/=\%"
set "QTIFW_ROOT=%QTIFW_ROOT:/=\%"
set "MINGW_ROOT=%MINGW_ROOT:/=\%"
set "APP_DIST_DIR=%APP_DIST_DIR:/=\%"
set "APP_BINARYCREATOR_EXECUTABLE=%APP_BINARYCREATOR_EXECUTABLE:/=\%"

REM Keep installer arch naming aligned with CMake's APP_PACKAGE_ARCH normalization.
if "%APP_PACKAGE_ARCH%"=="" (
  if not "%PROCESSOR_ARCHITEW6432%"=="" (
    set "APP_PACKAGE_ARCH=%PROCESSOR_ARCHITEW6432%"
  ) else (
    set "APP_PACKAGE_ARCH=%PROCESSOR_ARCHITECTURE%"
  )
)
if /I "%APP_PACKAGE_ARCH%"=="AMD64" set "APP_PACKAGE_ARCH=x86_64"
if /I "%APP_PACKAGE_ARCH%"=="X64" set "APP_PACKAGE_ARCH=x86_64"
if /I "%APP_PACKAGE_ARCH%"=="ARM64" set "APP_PACKAGE_ARCH=aarch64"
if /I "%APP_PACKAGE_ARCH%"=="AARCH64" set "APP_PACKAGE_ARCH=aarch64"
if /I "%APP_PACKAGE_ARCH%"=="X86" set "APP_PACKAGE_ARCH=x86"
if "%APP_PACKAGE_ARCH%"=="" set "APP_PACKAGE_ARCH=unknown"

REM Version from build\version.txt
set "VERSION=0.0.0"
if exist "%BUILD_DIR%\version.txt" (
  for /f "usebackq delims=" %%v in ("%BUILD_DIR%\version.txt") do set "VERSION=%%v"
)

echo [INFO] BUILD_DIR       = %BUILD_DIR%
echo [INFO] SRC_DIR         = %SRC_DIR%
echo [INFO] APP_SLUG        = %APP_SLUG%
echo [INFO] APP_ID          = %APP_ID%
echo [INFO] APP_DISPLAY_NAME= %APP_DISPLAY_NAME%
echo [INFO] APP_PACKAGE_ARCH= %APP_PACKAGE_ARCH%
echo [INFO] QT_ROOT         = %QT_ROOT%
echo [INFO] QTIFW_ROOT      = %QTIFW_ROOT%
echo [INFO] MINGW_ROOT      = %MINGW_ROOT%
echo [INFO] BINARYCREATOR   = %APP_BINARYCREATOR_EXECUTABLE%
echo [INFO] APP_DIST_DIR    = %APP_DIST_DIR%
echo [INFO] VERSION         = %VERSION%

if "%QT_ROOT%"=="" (
  echo [ERROR] QT_ROOT is empty. Configure with -DQT_ROOT=...
  exit /b 1
)
if "%APP_BINARYCREATOR_EXECUTABLE%"=="" (
  echo [ERROR] binarycreator.exe is empty. Configure with -DQTIFW_ROOT=... or ensure it is on PATH during configure.
  exit /b 1
)
if /I "%APP_BINARYCREATOR_EXECUTABLE%"=="APP_BINARYCREATOR_EXECUTABLE-NOTFOUND" (
  echo [ERROR] binarycreator.exe was not found during CMake configure.
  echo [HINT] Configure with -DQTIFW_ROOT=... or ensure binarycreator.exe is on PATH during configure.
  exit /b 1
)
if "%MINGW_ROOT%"=="" (
  echo [ERROR] MINGW_ROOT is empty. Configure with -DMINGW_ROOT=...
  exit /b 1
)

if not exist "%QT_ROOT%\bin\windeployqt.exe" (
  echo [ERROR] windeployqt.exe not found: %QT_ROOT%\bin\windeployqt.exe
  exit /b 1
)
if not exist "%APP_BINARYCREATOR_EXECUTABLE%" (
  echo [ERROR] binarycreator.exe not found: %APP_BINARYCREATOR_EXECUTABLE%
  exit /b 1
)

REM Choose CMake executable
set "CMAKE_EXE=cmake"
if defined CMAKE_COMMAND set "CMAKE_EXE=%CMAKE_COMMAND%"

set "BUILD_EXE=%BUILD_DIR%\%APP_SLUG%.exe"
if not exist "%BUILD_EXE%" (
  echo [WARN] Build-tree executable not found before install: %BUILD_EXE%
  echo [WARN] Continuing because cmake --install is the source of truth.
)

REM Stage prefix
set "STAGE_PREFIX=%BUILD_DIR%\ifw_stage\%APP_SLUG%-%VERSION%"
if exist "%STAGE_PREFIX%" rmdir /S /Q "%STAGE_PREFIX%"
mkdir "%STAGE_PREFIX%"

echo [INFO] CMake install -> stage prefix
"%CMAKE_EXE%" --install "%BUILD_DIR%" --prefix "%STAGE_PREFIX%"
if errorlevel 1 exit /b 1

set "STAGED_EXE=%STAGE_PREFIX%\bin\%APP_SLUG%.exe"
if not exist "%STAGED_EXE%" (
  echo [ERROR] Expected staged exe not found: %STAGED_EXE%
  exit /b 1
)

set "STAGE_ICON_DIR=%STAGE_PREFIX%\share\icons"
if not exist "%STAGE_ICON_DIR%" mkdir "%STAGE_ICON_DIR%"

if exist "%SRC_DIR%\packaging\icons\app_icon_win.ico" (
  copy /Y "%SRC_DIR%\packaging\icons\app_icon_win.ico" "%STAGE_ICON_DIR%\%APP_SLUG%.ico" >nul
) else (
  echo [WARN] Windows icon not found: %SRC_DIR%\packaging\icons\app_icon_win.ico
  echo [WARN] Shortcuts may fall back to the executable icon.
)

REM windeployqt into staged bin
echo [INFO] windeployqt on staged exe
"%QT_ROOT%\bin\windeployqt.exe" ^
  --release ^
  --no-translations ^
  --no-opengl-sw ^
  --dir "%STAGE_PREFIX%\bin" ^
  "%STAGED_EXE%"
if errorlevel 1 exit /b 1

if not exist "%STAGED_EXE%" (
  echo [WARN] %STAGED_EXE% missing after windeployqt; restoring from build tree.
  if not exist "%BUILD_EXE%" (
    echo [ERROR] Cannot restore staged exe because build-tree exe is missing: %BUILD_EXE%
    exit /b 1
  )
  copy /Y "%BUILD_EXE%" "%STAGE_PREFIX%\bin\" >nul
)

REM MinGW runtime DLLs
echo [INFO] Copy MinGW runtime DLLs
if exist "%MINGW_ROOT%\bin\libstdc++-6.dll"     copy /Y "%MINGW_ROOT%\bin\libstdc++-6.dll"     "%STAGE_PREFIX%\bin" >nul
if exist "%MINGW_ROOT%\bin\libgcc_s_seh-1.dll"  copy /Y "%MINGW_ROOT%\bin\libgcc_s_seh-1.dll"  "%STAGE_PREFIX%\bin" >nul
if exist "%MINGW_ROOT%\bin\libwinpthread-1.dll" copy /Y "%MINGW_ROOT%\bin\libwinpthread-1.dll" "%STAGE_PREFIX%\bin" >nul

REM IFW dirs in build tree
set "QTIFW_CONFIG_DIR=%BUILD_DIR%\qtifw\config"
set "QTIFW_PACKAGES_DIR=%BUILD_DIR%\qtifw\packages"
set "PKG_DIR=%QTIFW_PACKAGES_DIR%\%APP_ID%"
set "DATA_DIR=%PKG_DIR%\data"
set "CONFIG_XML=%QTIFW_CONFIG_DIR%\config.xml"

if not exist "%CONFIG_XML%" (
  echo [ERROR] Missing %CONFIG_XML%
  exit /b 1
)
if not exist "%PKG_DIR%\meta\package.xml" (
  echo [ERROR] Missing %PKG_DIR%\meta\package.xml
  exit /b 1
)

if exist "%DATA_DIR%" rmdir /S /Q "%DATA_DIR%"
mkdir "%DATA_DIR%"

echo [INFO] Copy staged tree into IFW package data
xcopy "%STAGE_PREFIX%\*" "%DATA_DIR%\" /E /I /Y >nul

if not exist "%DATA_DIR%\bin\%APP_SLUG%.exe" (
  echo [ERROR] bin\%APP_SLUG%.exe missing in package data
  exit /b 1
)

REM Build IFW installer
if not exist "%APP_DIST_DIR%" mkdir "%APP_DIST_DIR%"
set "OUTPUT_EXE_BUILD=%BUILD_DIR%\%APP_SLUG%-%VERSION%-Setup-%APP_PACKAGE_ARCH%.exe"
set "OUTPUT_EXE_DIST=%APP_DIST_DIR%\%APP_SLUG%-%VERSION%-Setup-%APP_PACKAGE_ARCH%.exe"

echo [INFO] binarycreator.exe
"%APP_BINARYCREATOR_EXECUTABLE%" -c "%CONFIG_XML%" -p "%QTIFW_PACKAGES_DIR%" "%OUTPUT_EXE_BUILD%"
if errorlevel 1 exit /b 1

copy /Y "%OUTPUT_EXE_BUILD%" "%OUTPUT_EXE_DIST%" >nul

echo [OK] Installer created:
echo      %OUTPUT_EXE_BUILD%
echo [OK] Copied to dist:
echo      %OUTPUT_EXE_DIST%
exit /b 0
