#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   packaging/scripts/make_installer_mac.sh build/mac-release
#   packaging/scripts/make_installer_mac.sh /abs/path/to/build/mac-release

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

BUILD_DIR_IN="${1:-}"
if [[ -z "${BUILD_DIR_IN}" ]]; then
  echo "Usage: $0 <build_dir>"
  exit 1
fi

if [[ "${BUILD_DIR_IN}" = /* ]]; then
  BUILD_DIR="$(cd "${BUILD_DIR_IN%/}" && pwd)"
else
  BUILD_DIR="$(cd "${PROJECT_ROOT}/${BUILD_DIR_IN%/}" && pwd)"
fi

if [[ ! -d "${BUILD_DIR}" ]]; then
  echo "[ERROR] Build directory does not exist: ${BUILD_DIR}"
  exit 1
fi

# Load packaging variables generated by CMake
ENV_FILE="${BUILD_DIR}/packaging/packaging.env.sh"
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "[ERROR] Missing ${ENV_FILE}"
  echo "[HINT] Re-run CMake configure so it generates build/.../packaging/packaging.env.sh"
  exit 1
fi
# shellcheck disable=SC1090
source "${ENV_FILE}"

normalize_package_arch() {
  case "$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')" in
    x86_64 | amd64) printf '%s\n' "x86_64" ;;
    aarch64 | arm64) printf '%s\n' "aarch64" ;;
    x86 | i386 | i486 | i586 | i686) printf '%s\n' "x86" ;;
    armv7l | armv7 | armhf) printf '%s\n' "armv7" ;;
    "") printf '%s\n' "unknown" ;;
    *) printf '%s\n' "$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')" ;;
  esac
}

APP_PACKAGE_ARCH="$(normalize_package_arch "${APP_PACKAGE_ARCH:-$(uname -m)}")"
DIST_DIR="${APP_DIST_DIR:-${PROJECT_ROOT}/dist}"

# Qt prefix
QT_PREFIX="${QT_ROOT:-}"
if [[ -z "${QT_PREFIX}" || ! -d "${QT_PREFIX}" ]]; then
  echo "[ERROR] QT_ROOT is not set or invalid."
  echo "[HINT] Set QT_ROOT in your mac preset to: /Users/<you>/Qt/6.x.y/macos"
  exit 1
fi

MACDEPLOYQT="${QT_PREFIX}/bin/macdeployqt"
if [[ ! -x "${MACDEPLOYQT}" ]]; then
  echo "[ERROR] macdeployqt not found or not executable: ${MACDEPLOYQT}"
  echo "[HINT] Your Qt installation may be incomplete or QT_ROOT is wrong."
  exit 1
fi

# Version from build/version.txt (generated by CMake)
VERSION_FILE="${BUILD_DIR}/version.txt"
VERSION="0.0.0"
if [[ -f "${VERSION_FILE}" ]]; then
  VERSION="$(tr -d ' \r\n' < "${VERSION_FILE}")"
fi

# --------- Versioned mac identity (important for multi-version installs)
VERSION_ID="${VERSION//./_}"                     # 1.0.0 -> 1_0_0
APP_ID_VERSIONED="${APP_ID}.${VERSION_ID}"       # com.swarmops.desktop.1_0_0
APP_DISPLAY_VERSIONED="${APP_DISPLAY_NAME} ${VERSION}"  # "SwarmOps 1.0.0"

echo "[INFO] PROJECT_ROOT        = ${PROJECT_ROOT}"
echo "[INFO] BUILD_DIR           = ${BUILD_DIR}"
echo "[INFO] APP_DISPLAY_NAME    = ${APP_DISPLAY_NAME}"
echo "[INFO] APP_DISPLAY_VERSION = ${APP_DISPLAY_VERSIONED}"
echo "[INFO] APP_SLUG            = ${APP_SLUG}"
echo "[INFO] APP_ID              = ${APP_ID}"
echo "[INFO] APP_ID_VERSIONED    = ${APP_ID_VERSIONED}"
echo "[INFO] ARCH                = ${APP_PACKAGE_ARCH}"
echo "[INFO] QT_PREFIX           = ${QT_PREFIX}"
echo "[INFO] macdeployqt         = ${MACDEPLOYQT}"
echo "[INFO] DIST_DIR            = ${DIST_DIR}"
echo "[INFO] VERSION             = ${VERSION}"

PLUTIL="/usr/bin/plutil"
if [[ ! -x "${PLUTIL}" ]]; then
  echo "[ERROR] plutil not found: ${PLUTIL}"
  exit 1
fi

# -------------------------------------------------------------------
# Stage install (cmake --install) into a versioned prefix
# -------------------------------------------------------------------
STAGE_PREFIX="${BUILD_DIR}/mac_stage/${APP_SLUG}-${VERSION}"
rm -rf "${STAGE_PREFIX}"
cmake --install "${BUILD_DIR}" --prefix "${STAGE_PREFIX}"

# -------------------------------------------------------------------
# Find staged .app bundle from the install tree
# -------------------------------------------------------------------
STAGED_APP_BUNDLE=""
if [[ -d "${STAGE_PREFIX}/${APP_SLUG}.app" ]]; then
  STAGED_APP_BUNDLE="${STAGE_PREFIX}/${APP_SLUG}.app"
else
  shopt -s nullglob
  APPS=( "${STAGE_PREFIX}"/*.app )
  shopt -u nullglob
  if [[ ${#APPS[@]} -gt 0 ]]; then
    STAGED_APP_BUNDLE="${APPS[0]}"
  fi
fi

if [[ -z "${STAGED_APP_BUNDLE}" || ! -d "${STAGED_APP_BUNDLE}" ]]; then
  echo "[ERROR] Expected staged .app bundle not found."
  echo "        Looked for:"
  echo "          ${STAGE_PREFIX}/${APP_SLUG}.app"
  echo "          ${STAGE_PREFIX}/*.app"
  echo "[HINT] Run: cmake --install ${BUILD_DIR} --prefix ${STAGE_PREFIX}"
  echo "       and inspect ${STAGE_PREFIX}"
  exit 1
fi

# -------------------------------------------------------------------
# Work directly on the staged bundle (VERSIONED NAME)
# -------------------------------------------------------------------
APP_BUNDLE_DIR="${STAGE_PREFIX}/${APP_DISPLAY_VERSIONED}.app"
if [[ "${STAGED_APP_BUNDLE}" != "${APP_BUNDLE_DIR}" ]]; then
  rm -rf "${APP_BUNDLE_DIR}"
  mv "${STAGED_APP_BUNDLE}" "${APP_BUNDLE_DIR}"
fi

APP_CONTENTS="${APP_BUNDLE_DIR}/Contents"
APP_MACOS="${APP_CONTENTS}/MacOS"
APP_RES="${APP_CONTENTS}/Resources"
APP_EXE="${APP_MACOS}/${APP_SLUG}"
PLIST="${APP_CONTENTS}/Info.plist"

if [[ ! -x "${APP_EXE}" ]]; then
  echo "[ERROR] Expected staged app executable not found: ${APP_EXE}"
  exit 1
fi
if [[ ! -f "${PLIST}" ]]; then
  echo "[ERROR] Expected staged Info.plist not found: ${PLIST}"
  exit 1
fi

mkdir -p "${APP_RES}"

echo "[INFO] STAGED_APP_BUNDLE   = ${APP_BUNDLE_DIR}"
echo "[INFO] APP_EXE             = ${APP_EXE}"

# -------------------------------------------------------------------
# Normalize bundle metadata and resources in the staged app
# -------------------------------------------------------------------
ICON_ICNS="${PROJECT_ROOT}/packaging/icons/app_icon_mac.icns"
ICON_KEY=""
if [[ -f "${ICON_ICNS}" ]]; then
  ICON_KEY="${APP_SLUG}"
  cp -f "${ICON_ICNS}" "${APP_RES}/${APP_SLUG}.icns"
else
  echo "[WARN] mac icon not found: ${ICON_ICNS} (app will use default icon)"
fi

"${PLUTIL}" -replace CFBundleName -string "${APP_DISPLAY_VERSIONED}" "${PLIST}"
"${PLUTIL}" -replace CFBundleDisplayName -string "${APP_DISPLAY_VERSIONED}" "${PLIST}"
"${PLUTIL}" -replace CFBundleIdentifier -string "${APP_ID_VERSIONED}" "${PLIST}"
"${PLUTIL}" -replace CFBundleVersion -string "${VERSION}" "${PLIST}"
"${PLUTIL}" -replace CFBundleShortVersionString -string "${VERSION}" "${PLIST}"
"${PLUTIL}" -replace LSMinimumSystemVersion -string "11.0" "${PLIST}"
"${PLUTIL}" -replace NSHighResolutionCapable -bool YES "${PLIST}"
if [[ -n "${ICON_KEY}" ]]; then
  "${PLUTIL}" -replace CFBundleIconFile -string "${ICON_KEY}" "${PLIST}"
fi

# -------------------------------------------------------------------
# qt.conf (ensures Qt searches plugins inside the bundle)
# -------------------------------------------------------------------
cat > "${APP_RES}/qt.conf" <<'EOF'
[Paths]
Plugins=PlugIns
EOF

# -------------------------------------------------------------------
# Bundle resources into the .app
# The install tree keeps app resources in share/<slug>/resources.
# Mirror them into the staged bundle before running macdeployqt.
# -------------------------------------------------------------------
RES_SRC="${STAGE_PREFIX}/share/${APP_SLUG}/resources"
if [[ -d "${RES_SRC}" ]]; then
  mkdir -p "${APP_RES}/resources"
  cp -a "${RES_SRC}/." "${APP_RES}/resources/"
fi

# -------------------------------------------------------------------
# Run macdeployqt to bundle Qt frameworks/plugins
# -------------------------------------------------------------------
echo "[INFO] Running macdeployqt..."
"${MACDEPLOYQT}" "${APP_BUNDLE_DIR}" -always-overwrite -verbose=2

QCOCOA="${APP_BUNDLE_DIR}/Contents/PlugIns/platforms/libqcocoa.dylib"
if [[ ! -f "${QCOCOA}" ]]; then
  echo "[ERROR] Qt platform plugin libqcocoa.dylib was not deployed:"
  echo "        ${QCOCOA}"
  exit 1
fi

FW_DIR="@executable_path/../Frameworks"

echo "[INFO] Patching rpaths for ${APP_EXE}"
# Add rpath to Frameworks (ignore if exists)
install_name_tool -add_rpath "${FW_DIR}" "${APP_EXE}" 2>/dev/null || true

# Ensure Qt frameworks are referenced via @rpath (safety)
for fw in QtCore QtGui QtWidgets; do
  if [[ -d "${APP_BUNDLE_DIR}/Contents/Frameworks/${fw}.framework" ]]; then
    install_name_tool -change \
      "${QT_PREFIX}/lib/${fw}.framework/Versions/A/${fw}" \
      "@rpath/${fw}.framework/Versions/A/${fw}" \
      "${APP_EXE}" 2>/dev/null || true
  fi
done

echo "[INFO] RPATHs now:"
otool -l "${APP_EXE}" | awk '/LC_RPATH/{p=1} p{print} /path/{p=0}'

# -------------------------------------------------------------------
# Create DMG (VERSIONED)
# -------------------------------------------------------------------
mkdir -p "${DIST_DIR}"

DMG_NAME="${APP_SLUG}-${VERSION}-macOS-${APP_PACKAGE_ARCH}.dmg"
DMG_BUILD="${BUILD_DIR}/${DMG_NAME}"
DMG_DIST="${DIST_DIR}/${DMG_NAME}"

DMG_STAGING="${BUILD_DIR}/_dmg_staging"
rm -rf "${DMG_STAGING}"
mkdir -p "${DMG_STAGING}"

cp -a "${APP_BUNDLE_DIR}" "${DMG_STAGING}/"
ln -s /Applications "${DMG_STAGING}/Applications" || true

echo "[INFO] Creating DMG..."
hdiutil create -volname "${APP_DISPLAY_VERSIONED}" \
  -srcfolder "${DMG_STAGING}" \
  -ov -format UDZO \
  "${DMG_BUILD}"

cp -f "${DMG_BUILD}" "${DMG_DIST}"

echo "[OK] DMG created:"
echo "     ${DMG_BUILD}"
echo "[OK] Copied to dist:"
echo "     ${DMG_DIST}"

rm -rf "${DMG_STAGING}" || true
