#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   packaging/scripts/make_installer_linux.sh build/release
#   packaging/scripts/make_installer_linux.sh /abs/path/to/build/release

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

BUILD_DIR_IN="${1:-}"
if [[ -z "${BUILD_DIR_IN}" ]]; then
  echo "Usage: $0 <build_dir>"
  exit 1
fi

if [[ "${BUILD_DIR_IN}" = /* ]]; then
  BUILD_DIR="$(cd "${BUILD_DIR_IN%/}" && pwd)"
else
  BUILD_DIR="$(cd "${PROJECT_ROOT}/${BUILD_DIR_IN%/}" && pwd)"
fi

if [[ ! -d "${BUILD_DIR}" ]]; then
  echo "[ERROR] Build directory does not exist: ${BUILD_DIR}"
  exit 1
fi

# Load packaging variables generated by CMake
ENV_FILE="${BUILD_DIR}/packaging/packaging.env.sh"
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "[ERROR] Missing ${ENV_FILE}"
  echo "[HINT] Re-run CMake configure so it generates build/packaging/packaging.env"
  exit 1
fi
# shellcheck disable=SC1090
source "${ENV_FILE}"

normalize_package_arch() {
  case "$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')" in
    x86_64 | amd64) printf '%s\n' "x86_64" ;;
    aarch64 | arm64) printf '%s\n' "aarch64" ;;
    x86 | i386 | i486 | i586 | i686) printf '%s\n' "x86" ;;
    armv7l | armv7 | armhf) printf '%s\n' "armv7" ;;
    "") printf '%s\n' "unknown" ;;
    *) printf '%s\n' "$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')" ;;
  esac
}

APP_PACKAGE_ARCH="$(normalize_package_arch "${APP_PACKAGE_ARCH:-$(uname -m)}")"
DIST_DIR="${APP_DIST_DIR:-${PROJECT_ROOT}/dist}"

find_binarycreator() {
  local candidate

  for candidate in \
    "${APP_BINARYCREATOR_EXECUTABLE:-}" \
    "${QTIFW_ROOT:+${QTIFW_ROOT}/bin/binarycreator}"
  do
    if [[ -n "${candidate}" && -x "${candidate}" ]]; then
      printf '%s\n' "${candidate}"
      return 0
    fi
  done

  candidate="$(command -v binarycreator 2>/dev/null || true)"
  if [[ -n "${candidate}" && -x "${candidate}" ]]; then
    printf '%s\n' "${candidate}"
    return 0
  fi

  if [[ -n "${HOME:-}" && -d "${HOME}/Qt/Tools/QtInstallerFramework" ]]; then
    while IFS= read -r candidate; do
      if [[ -x "${candidate}" ]]; then
        printf '%s\n' "${candidate}"
        return 0
      fi
    done < <(
      find "${HOME}/Qt/Tools/QtInstallerFramework" \
        -mindepth 3 \
        -maxdepth 3 \
        -type f \
        -path '*/bin/binarycreator' \
        -print 2>/dev/null | sort -V -r
    )
  fi

  return 1
}

validate_staged_binary_dependencies() {
  local binary="$1"
  local unresolved=""

  if ! command -v ldd >/dev/null 2>&1; then
    echo "[WARN] ldd not found; skipping staged binary dependency check."
    return 0
  fi

  unresolved="$(ldd "${binary}" | awk '/not found/ { print }' || true)"
  if [[ -n "${unresolved}" ]]; then
    echo "[ERROR] Staged binary has unresolved shared libraries: ${binary}"
    echo "${unresolved}"
    echo "[HINT] Check the app INSTALL_RPATH and the deployed lib directory."
    exit 1
  fi
}

copy_with_symlink_target() {
  local source_path="$1"
  local dest_dir="$2"
  local real_path

  mkdir -p "${dest_dir}"
  cp -a "${source_path}" "${dest_dir}/"

  if [[ -L "${source_path}" ]]; then
    real_path="$(readlink -f "${source_path}")"
    if [[ -n "${real_path}" && -f "${real_path}" ]]; then
      cp -a "${real_path}" "${dest_dir}/"
    fi
  fi
}

copy_qt_library_dependencies() {
  local binary="$1"
  local dep
  local real_dep
  local qt_lib_prefix="${QT_ROOT%/}/lib/"

  if ! command -v ldd >/dev/null 2>&1; then
    echo "[WARN] ldd not found; skipping Qt dependency copy for ${binary}."
    return 0
  fi

  while IFS= read -r dep; do
    [[ -f "${dep}" ]] || continue
    real_dep="$(readlink -f "${dep}")"
    [[ "${real_dep}" == "${qt_lib_prefix}"* ]] || continue
    copy_with_symlink_target "${dep}" "${STAGE_PREFIX}/lib"
  done < <(
    ldd "${binary}" |
      awk -v prefix="${QT_ROOT%/}/" '{
        for (i = 1; i <= NF; ++i) {
          if (index($i, prefix) == 1) {
            print $i
          }
        }
      }' |
      sort -u
  )
}

copy_qt_library_family() {
  local label="$1"
  local lib_dir="$2"
  local name_pattern="$3"
  local required="${4:-required}"
  local lib
  local libs=()

  if [[ -d "${lib_dir}" ]]; then
    while IFS= read -r lib; do
      libs+=("${lib}")
    done < <(find "${lib_dir}" -maxdepth 1 \( -type f -o -type l \) -name "${name_pattern}" -print | sort -V)
  fi

  if (( ${#libs[@]} == 0 )); then
    if [[ "${required}" == "optional" ]]; then
      echo "[INFO] Optional Qt library not found, skipping: ${lib_dir}/${name_pattern}"
    else
      echo "[WARN] Qt library not found, skipping: ${lib_dir}/${name_pattern}"
    fi
    return 0
  fi

  echo "[INFO] Bundling ${label}:"
  for lib in "${libs[@]}"; do
    echo "       - ${lib}"
    copy_with_symlink_target "${lib}" "${STAGE_PREFIX}/lib"
  done
}

copy_qt_plugin_file() {
  local relative_path="$1"
  local required="${2:-required}"
  local label="${3:-}"
  local source_path="${QT_ROOT%/}/plugins/${relative_path}"
  local dest_dir="${STAGE_PREFIX}/plugins/$(dirname "${relative_path}")"

  if [[ ! -f "${source_path}" ]]; then
    if [[ "${required}" == "optional" ]]; then
      echo "[INFO] Optional Qt plugin not found, skipping: ${source_path}"
    else
      echo "[WARN] Qt plugin not found, skipping: ${source_path}"
    fi
    return 0
  fi

  if [[ -n "${label}" ]]; then
    echo "[INFO] Bundling ${label}: ${source_path}"
  fi

  copy_with_symlink_target "${source_path}" "${dest_dir}"
  copy_qt_library_dependencies "${source_path}"
}

copy_qt_plugin_dir() {
  local relative_dir="$1"
  local required="${2:-required}"
  local label="${3:-}"
  local source_dir="${QT_ROOT%/}/plugins/${relative_dir}"
  local plugin

  if [[ ! -d "${source_dir}" ]]; then
    if [[ "${required}" == "optional" ]]; then
      echo "[INFO] Optional Qt plugin directory not found, skipping: ${source_dir}"
    else
      echo "[WARN] Qt plugin directory not found, skipping: ${source_dir}"
    fi
    return 0
  fi

  if [[ -n "${label}" ]]; then
    echo "[INFO] Bundling ${label} from ${source_dir}"
  fi

  while IFS= read -r plugin; do
    copy_qt_plugin_file "${relative_dir}/$(basename "${plugin}")" "${required}"
  done < <(find "${source_dir}" -maxdepth 1 -type f -name '*.so' -print | sort)
}

deploy_linux_qt_plugins() {
  if [[ -z "${QT_ROOT:-}" || ! -d "${QT_ROOT%/}/plugins" ]]; then
    echo "[ERROR] QT_ROOT is empty or missing plugins directory: ${QT_ROOT:-}"
    exit 1
  fi

  copy_qt_plugin_file "platforms/libqxcb.so" "required" "XCB platform plugin"
  copy_qt_plugin_file "platforms/libqwayland.so" "optional" "Wayland platform plugin"
  copy_qt_plugin_dir "xcbglintegrations"
  copy_qt_plugin_dir "wayland-graphics-integration-client" "optional" "Wayland graphics integration plugins"
  copy_qt_plugin_dir "wayland-decoration-client" "optional" "Wayland decoration plugins"
  copy_qt_plugin_dir "wayland-shell-integration" "optional" "Wayland shell integration plugins"
  copy_qt_library_family "Qt Wayland client libraries" "${QT_ROOT%/}/lib" "libQt6WaylandClient.so*" "optional"
  copy_qt_plugin_file "platformthemes/libqxdgdesktopportal.so" "optional" "XDG desktop portal platform theme plugin"
  copy_qt_plugin_file "platformthemes/libqgtk3.so" "optional" "GTK3 platform theme plugin"
  copy_qt_plugin_file "platforminputcontexts/libcomposeplatforminputcontextplugin.so" "optional" "Compose input context plugin"
  copy_qt_plugin_dir "imageformats"
  copy_qt_plugin_dir "iconengines" "optional" "Qt icon engine plugins"
}

validate_staged_qt_plugins() {
  local plugin
  local unresolved=""

  if ! command -v ldd >/dev/null 2>&1; then
    echo "[WARN] ldd not found; skipping staged Qt plugin dependency check."
    return 0
  fi

  while IFS= read -r plugin; do
    unresolved="$(ldd "${plugin}" | awk '/not found/ { print }' || true)"
    if [[ -n "${unresolved}" ]]; then
      echo "[ERROR] Staged Qt plugin has unresolved shared libraries: ${plugin}"
      echo "${unresolved}"
      echo "[HINT] Install the missing system runtime package or bundle the needed Qt dependency."
      exit 1
    fi
  done < <(find "${STAGE_PREFIX}/plugins" -type f -name '*.so' -print)
}

# IFW binarycreator
IFW_BIN="$(find_binarycreator || true)"
if [[ -z "${IFW_BIN}" ]]; then
  echo "[ERROR] binarycreator not found."
  echo "[HINT] Install Qt Installer Framework with the Qt Maintenance Tool."
  echo "[HINT] Expected locations include:"
  echo "       -DQTIFW_ROOT=/path/to/Qt/Tools/QtInstallerFramework/<version>"
  echo "       PATH containing binarycreator"
  echo "       ${HOME:-\$HOME}/Qt/Tools/QtInstallerFramework/<version>/bin/binarycreator"
  exit 1
fi

# Version from build/version.txt
VERSION_FILE="${BUILD_DIR}/version.txt"
VERSION="0.0.0"
if [[ -f "${VERSION_FILE}" ]]; then
  VERSION="$(tr -d ' \r\n' < "${VERSION_FILE}")"
fi

# IFW layout generated by CMake
QTIFW_CONFIG_XML="${BUILD_DIR}/qtifw/config/config.xml"
QTIFW_PACKAGES_ROOT="${BUILD_DIR}/qtifw/packages"
QTIFW_PACKAGE_DIR="${QTIFW_PACKAGES_ROOT}/${APP_ID}"

if [[ ! -f "${QTIFW_CONFIG_XML}" ]]; then
  echo "[ERROR] Missing ${QTIFW_CONFIG_XML} (CMake did not generate IFW config)"
  exit 1
fi
if [[ ! -d "${QTIFW_PACKAGE_DIR}/meta" ]]; then
  echo "[ERROR] Missing ${QTIFW_PACKAGE_DIR}/meta (CMake did not generate package meta)"
  exit 1
fi

echo "[INFO] PROJECT_ROOT = ${PROJECT_ROOT}"
echo "[INFO] BUILD_DIR    = ${BUILD_DIR}"
echo "[INFO] APP_SLUG     = ${APP_SLUG}"
echo "[INFO] APP_ID       = ${APP_ID}"
echo "[INFO] ARCH         = ${APP_PACKAGE_ARCH}"
echo "[INFO] IFW_BIN      = ${IFW_BIN}"
echo "[INFO] DIST_DIR     = ${DIST_DIR}"
echo "[INFO] VERSION      = ${VERSION}"

# Stage prefix (generic)
STAGE_PREFIX="${BUILD_DIR}/ifw_stage/${APP_SLUG}-${VERSION}"
rm -rf "${STAGE_PREFIX}"

cmake --install "${BUILD_DIR}" --prefix "${STAGE_PREFIX}"

mkdir -p \
  "${STAGE_PREFIX}/bin" \
  "${STAGE_PREFIX}/lib" \
  "${STAGE_PREFIX}/share/applications" \
  "${STAGE_PREFIX}/share/icons/hicolor/512x512/apps"

STAGED_BIN="${STAGE_PREFIX}/bin/${APP_SLUG}"
if [[ ! -x "${STAGED_BIN}" ]]; then
  echo "[ERROR] Expected binary not found: ${STAGED_BIN}"
  exit 1
fi

# Rename binary to versioned name
mv -f "${STAGE_PREFIX}/bin/${APP_SLUG}" "${STAGE_PREFIX}/bin/${APP_SLUG}-${VERSION}"
chmod 0755 "${STAGE_PREFIX}/bin/${APP_SLUG}-${VERSION}"

deploy_linux_qt_plugins
validate_staged_binary_dependencies "${STAGE_PREFIX}/bin/${APP_SLUG}-${VERSION}"
validate_staged_qt_plugins

# Fill IFW package data
DATA_DIR="${QTIFW_PACKAGE_DIR}/data"
rm -rf "${DATA_DIR}"
mkdir -p "${DATA_DIR}"

shopt -s dotglob
cp -a "${STAGE_PREFIX}/." "${DATA_DIR}/"
shopt -u dotglob

# Build offline IFW installer
mkdir -p "${DIST_DIR}"

OUT_RUN_BUILD="${BUILD_DIR}/${APP_SLUG}-${VERSION}-Setup-${APP_PACKAGE_ARCH}.run"
OUT_RUN_DIST="${DIST_DIR}/${APP_SLUG}-${VERSION}-Setup-${APP_PACKAGE_ARCH}.run"

"${IFW_BIN}" --offline-only \
  -c "${QTIFW_CONFIG_XML}" \
  -p "${QTIFW_PACKAGES_ROOT}" \
  "${OUT_RUN_BUILD}"

cp -f "${OUT_RUN_BUILD}" "${OUT_RUN_DIST}"
chmod +x "${OUT_RUN_BUILD}" "${OUT_RUN_DIST}"

echo "[OK] Installer created:"
echo "     ${OUT_RUN_BUILD}"
echo "[OK] Copied to dist:"
echo "     ${OUT_RUN_DIST}"
echo
echo "System-wide install (requires sudo if target is /opt or /usr):"
echo "  sudo \"${OUT_RUN_DIST}\""
